package models;

import java.util.logging.Level;
import utilities.GameLog;
import contracts.InstructionStatus;

/**
 * An instruction is the specific command that is generated by the game.
 * @author heshamsalman
 *
 */
public class Instruction {
	private InstructionStatus status;

	public Instruction(InstructionStatus status) {
		this.status = status;
	}

	public InstructionStatus getStatus() {
		return status;
	}

	public void setStatus(InstructionStatus status) {
		GameLog.log.entering(getClass().getName(), "setStatus");
		if (status != null && status != this.status) {
			GameLog.log.log(Level.INFO, "Instruction" + ": changing status from " + this.status + " to " + status);
			this.status = status;
		}
		GameLog.log.exiting(getClass().getName(), "setStatus");
	}
}
