package models;

import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.Logger.*;

import misc.UnsupportedStatusTransitionException;
import contracts.InstructionStatus;

/**
 * An instruction is the specific command that is generated by the game to tell the user to press up, down, etc...,
 * @author heshamsalman
 *
 */
public class Instruction {
	private InstructionStatus status;
	private UUID id;
	private static final Logger logger = Logger.getLogger(Instruction.class.getName());
	
	public Instruction(InstructionStatus status) {
		this.status = status;
		id = UUID.randomUUID();
	}
	
	public InstructionStatus getStatus() {
		return status;
	}
	
	
	public void setStatus(InstructionStatus status) {
		logger.entering(getClass().getName(), "setStatus");
		if (status != null && status != this.status) {
			logger.log(Level.INFO, "Instruction#" + id + ": cahnging status from " + this.status + " to " + status);
			this.status = status;
		}
		logger.exiting(getClass().getName(), "setStatus");
	}
}
